services:
  user-db:
    image: mongo:latest
    container_name: user-db
    mem_limit: 512m
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${USER_DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${USER_DB_PASSWORD}"
      MONGO_INITDB_DATABASE: "${USER_DB_NAME}"
    ports:
      - "5433:27017"
    extends:
      file: ./common-config.yml
      service: network-deploy-service
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    mem_limit: 512m
    depends_on:
      - user-db
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://${USER_DB_USERNAME}:${USER_DB_PASSWORD}@user-db:27017/${USER_DB_NAME}?authSource=admin"
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: "${USER_DB_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${USER_DB_PASSWORD}"
    ports:
      - "8089:8081"
    extends:
      file: ./common-config.yml
      service: network-deploy-service
  product-db:
    image: postgres:latest
    container_name: product-db
    mem_limit: 512m
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      POSTGRES_USER: "${PRODUCT_DB_USERNAME}"
      POSTGRES_PASSWORD: "${PRODUCT_DB_PASSWORD}"
      POSTGRES_DB: "${PRODUCT_DB_NAME}"
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: ./common-config.yml
      service: network-deploy-service
  order-db:
    image: postgres:latest
    container_name: order-db
    mem_limit: 512m
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      POSTGRES_USER: "${ORDER_DB_USERNAME}"
      POSTGRES_PASSWORD: "${ORDER_DB_PASSWORD}"
      POSTGRES_DB: "${ORDER_DB_NAME}"
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: ./common-config.yml
      service: network-deploy-service
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT:-5672}:${RABBITMQ_PORT:-5672}"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-guest}
      RABBITMQ_DEFAULT_PASSWORD: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 30s
    extends:
      file: ./common-config.yml
      service: network-deploy-service
  configserver:
    image: ecommerce/configserver
    container_name: configserver
    mem_limit: 512m
    deploy:
      resources:
        limits:
          memory: 512m
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      CONFIG_REPO_PASSWORD: "${CONFIG_REPO_PASSWORD}"
      ENCRYPT_KEY: "${ENCRYPT_KEY}"
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8888/actuator/health/readiness || exit 1"
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "8888:8888"
    extends:
      file: ./common-config.yml
      service: network-deploy-service
  eureka:
    image: ecommerce/eureka
    container_name: eureka
    mem_limit: 512m
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512m
    ports:
      - "8761:8761"
    extends:
      file: ./common-config.yml
      service: network-deploy-service
  userMS:
    image: ecommerce/user-ms
    container_name: userMS
    mem_limit: 512m
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      CONFIGSERVER_URI: http://configserver:8888
    ports:
      - "8082:8082"
    extends:
      file: ./common-config.yml
      service: network-deploy-service
  productMS:
    image: ecommerce/product-ms
    container_name: productMS
    mem_limit: 512m
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      CONFIGSERVER_URI: http://configserver:8888
    ports:
      - "8081:8081"
    extends:
      file: ./common-config.yml
      service: network-deploy-service
  orderMS:
    image: ecommerce/order-ms
    container_name: orderMS
    mem_limit: 512m
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      CONFIGSERVER_URI: http://configserver:8888
    ports:
      - "8083:8083"
    extends:
      file: ./common-config.yml
      service: network-deploy-service
  gateway:
    image: ecommerce/gateway
    container_name: gateway
    mem_limit: 512m
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512m
    ports:
      - "8080:8080"
    environment:
      CONFIGSERVER_URI: http://configserver:8888
    extends:
      file: ./common-config.yml
      service: network-deploy-service
networks:
  ecommerce:
    driver: bridge
