spring:
  rabbitmq:
    host: ${spring.rabbitmq.host:localhost}
    port: ${spring.rabbitmq.port:5672}
    username: ${spring.rabbitmq.username:guest}
    password: ${spring.rabbitmq.password}
  config:
    import: optional:configserver:${CONFIGSERVER_URI:http://localhost:8888}
  application:
    name: userMS
  mongodb:
    uri: ${db.url}
    database: ${db.name}
    username: ${db.username}
    password: ${db.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  #    env:
  #      show-values: always
  info:
    env:
      enabled: true

server:
  shutdown: graceful
  port: ${USER_PORT:8082}

eureka:
  client:
    fetch-registry: ${eureka.client.fetch-registry:true}
    service-url:
      defaultZone: ${eureka.client.service-url.defaultZone}
    register-with-eureka: ${eureka.client.register-with-eureka:true}

info:
  app:
    name: ${info.app.name}
    description: ${info.app.description}
    version: ${info.app.version}
    profile: ${spring.profiles.active}
