spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI:https://github.com/MiguelosAguialos/microservices-configs.git}
          default-label: ${CONFIG_REPO_DEFAULT_LABEL:main}
          username: ${CONFIG_REPO_USERNAME:MiguelosAguialos}
          password: ${CONFIG_REPO_PASSWORD:}
server:
  port: ${CONFIGSERVER_PORT:8888}
  shutdown: graceful

encrypt:
  key: ${ENCRYPT_KEY:}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    env:
      enabled: true

logging:
  level:
    org.springframework.cloud.config.server: INFO
